version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ccps
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass

  web:
    build: .
    image: ccps:dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env.dev
